#!/bin/bash
# Start 0K ATHENA Dashboard Server
# Usage: ./start.sh [--reload]

DIR="$(cd "$(dirname "$0")" && pwd)"
VENV="$DIR/.venv"
ENV_FILE="$DIR/.env"
ENV_EXAMPLE="$DIR/.env.example"

if [ ! -d "$VENV" ]; then
    echo "Creating virtual environment..."
    python3 -m venv "$VENV"
    "$VENV/bin/pip" install -r "$DIR/requirements.txt"
fi

# ── Pre-install Playwright chromium so agents don't waste tool calls ──
if command -v npx &>/dev/null; then
    npx playwright install chromium --with-deps 2>/dev/null || true
fi

ARGS="server:app --host 127.0.0.1 --port 8080"
if [ "$1" = "--reload" ]; then
    ARGS="$ARGS --reload"
fi

# ── First-run wizard: generate .env if it doesn't exist ──
if [ ! -f "$ENV_FILE" ]; then
    echo ""
    echo "  First-run setup — generating .env configuration"
    echo "  ────────────────────────────────────────────────"
    echo "  Press Enter to accept defaults shown in [brackets]."
    echo ""

    read -p "  Neo4j URI [bolt://localhost:7687]: " neo4j_uri
    neo4j_uri="${neo4j_uri:-bolt://localhost:7687}"

    read -p "  Neo4j User [neo4j]: " neo4j_user
    neo4j_user="${neo4j_user:-neo4j}"

    read -sp "  Neo4j Password: " neo4j_pass
    echo ""

    read -p "  Kali External URL [http://localhost:5000]: " kali_ext
    kali_ext="${kali_ext:-http://localhost:5000}"

    read -p "  Kali Internal URL (optional, press Enter to skip): " kali_int

    read -p "  Kali API Key (optional, press Enter to skip): " kali_key

    cat > "$ENV_FILE" << EOF
# 0K ATHENA Dashboard — Local Configuration (DO NOT COMMIT)
# Generated by first-run wizard on $(date +%Y-%m-%d)
NEO4J_URI=${neo4j_uri}
NEO4J_USER=${neo4j_user}
NEO4J_PASS=${neo4j_pass}
KALI_EXTERNAL_URL=${kali_ext}
KALI_INTERNAL_URL=${kali_int}
KALI_API_KEY=${kali_key}
EOF
    chmod 600 "$ENV_FILE"
    echo ""
    echo "  Configuration saved to .env (owner-only permissions)"
    echo ""
fi

echo ""
echo "  0K ATHENA Dashboard"
echo "  ───────────────────"
echo "  http://localhost:8080"

# Auth source indicator (for diagnostics)
if [ -n "$NEO4J_PASS" ]; then
    echo "  Neo4j:      env var ✓"
elif grep -q "^NEO4J_PASS=.\+" "$ENV_FILE" 2>/dev/null; then
    echo "  Neo4j:      .env file ✓"
else
    # Try 1Password as last resort
    if command -v op &>/dev/null; then
        export NEO4J_PASS=$(op read "op://Private/Neo4j ATHENA/password" 2>/dev/null)
        if [ -n "$NEO4J_PASS" ]; then
            echo "  Neo4j:      1Password ✓"
        else
            echo "  Neo4j:      No password — set NEO4J_PASS, edit .env, or run 'op signin'"
        fi
    else
        echo "  Neo4j:      No password — edit .env or set NEO4J_PASS"
    fi
fi

echo ""

cd "$DIR" && exec "$VENV/bin/uvicorn" $ARGS
