#!/bin/bash
# Start 0K ATHENA Dashboard Server
# Usage: ./start.sh [--reload]

DIR="$(cd "$(dirname "$0")" && pwd)"
VENV="$DIR/.venv"
ENV_FILE="$DIR/.env"
ENV_EXAMPLE="$DIR/.env.example"

if [ ! -d "$VENV" ]; then
    echo "Creating virtual environment..."
    python3 -m venv "$VENV"
    "$VENV/bin/pip" install -r "$DIR/requirements.txt"
fi

# ── Pre-install Playwright chromium so agents don't waste tool calls ──
if command -v npx &>/dev/null; then
    npx playwright install chromium --with-deps 2>/dev/null || true
fi

ARGS="server:app --host 127.0.0.1 --port 8080"
if [ "$1" = "--reload" ]; then
    ARGS="$ARGS --reload"
fi

# ── First-run wizard: generate .env if it doesn't exist ──
if [ ! -f "$ENV_FILE" ]; then
    echo ""
    echo "  First-run setup — generating .env configuration"
    echo "  ────────────────────────────────────────────────"
    echo "  Press Enter to accept defaults shown in [brackets]."
    echo ""

    read -p "  Neo4j URI [bolt://localhost:7687]: " neo4j_uri
    neo4j_uri="${neo4j_uri:-bolt://localhost:7687}"

    read -p "  Neo4j User [neo4j]: " neo4j_user
    neo4j_user="${neo4j_user:-neo4j}"

    read -sp "  Neo4j Password: " neo4j_pass
    echo ""

    read -p "  Kali External URL [http://localhost:5000]: " kali_ext
    kali_ext="${kali_ext:-http://localhost:5000}"

    read -p "  Kali Internal URL (optional, press Enter to skip): " kali_int

    read -p "  Kali API Key (optional, press Enter to skip): " kali_key

    cat > "$ENV_FILE" << EOF
# 0K ATHENA Dashboard — Local Configuration (DO NOT COMMIT)
# Generated by first-run wizard on $(date +%Y-%m-%d)
NEO4J_URI=${neo4j_uri}
NEO4J_USER=${neo4j_user}
NEO4J_PASS=${neo4j_pass}
KALI_EXTERNAL_URL=${kali_ext}
KALI_INTERNAL_URL=${kali_int}
KALI_API_KEY=${kali_key}
EOF
    chmod 600 "$ENV_FILE"
    echo ""
    echo "  Configuration saved to .env (owner-only permissions)"
    echo ""
fi

echo ""
echo "  0K ATHENA Dashboard"
echo "  ───────────────────"
echo "  http://localhost:8080"

# Auth source indicator (for diagnostics)
if [ -n "$NEO4J_PASS" ]; then
    echo "  Neo4j:      env var ✓"
elif grep -q "^NEO4J_PASS=.\+" "$ENV_FILE" 2>/dev/null; then
    echo "  Neo4j:      .env file ✓"
else
    # Try 1Password as last resort
    if command -v op &>/dev/null; then
        export NEO4J_PASS=$(op read "op://Private/laespix2zshux5xuon73x7wt2y/password" 2>/dev/null)
        if [ -n "$NEO4J_PASS" ]; then
            echo "  Neo4j:      1Password ✓"
        else
            echo "  Neo4j:      No password — set NEO4J_PASS, edit .env, or run 'op signin'"
        fi
    else
        echo "  Neo4j:      No password — edit .env or set NEO4J_PASS"
    fi
fi

# ── H1: Graphiti Cross-Session Memory (Anthropic API key from 1Password) ──
if [ -z "$ANTHROPIC_API_KEY" ]; then
    if command -v op &>/dev/null; then
        export ANTHROPIC_API_KEY=$(op read "op://Vex/Athena-Graphiti API/credential" 2>/dev/null)
        # Graphiti embedder needs OpenAI for text-embedding-3-small
        if [ -z "$OPENAI_API_KEY" ]; then
            export OPENAI_API_KEY=$(op read "op://Vex/OpenAI API/credential" 2>/dev/null)
        fi
        if [ -n "$ANTHROPIC_API_KEY" ]; then
            echo "  Graphiti:   1Password (Haiku 4.5 + OpenAI embeddings) ✓"
        else
            echo "  Graphiti:   No API key — cross-session memory disabled"
        fi
    else
        echo "  Graphiti:   No 1Password CLI — cross-session memory disabled"
    fi
else
    echo "  Graphiti:   env var ✓"
fi

# ── H3: Langfuse LLM Observability ──
LANGFUSE_ENV="$DIR/docker/.env.langfuse"
LANGFUSE_COMPOSE="$DIR/docker/docker-compose.langfuse.yml"
if [ -z "$LANGFUSE_SECRET_KEY" ]; then
    # Bridge from Docker env file if it exists
    if [ -f "$LANGFUSE_ENV" ]; then
        export LANGFUSE_SECRET_KEY=$(grep "^LANGFUSE_PROJECT_SECRET_KEY=" "$LANGFUSE_ENV" | cut -d= -f2)
        if [ -n "$LANGFUSE_SECRET_KEY" ]; then
            echo "  Langfuse:   docker/.env.langfuse ✓"
        else
            echo "  Langfuse:   Key not found in docker/.env.langfuse"
        fi
    else
        echo "  Langfuse:   Not configured — observability disabled"
    fi
else
    echo "  Langfuse:   env var ✓"
fi

# Auto-start Langfuse Docker stack if configured
if [ -n "$LANGFUSE_SECRET_KEY" ] && [ -f "$LANGFUSE_COMPOSE" ]; then
    if command -v docker &>/dev/null; then
        # Check if Docker daemon is running
        if docker info &>/dev/null 2>&1; then
            # Check if Langfuse containers are already running
            LANGFUSE_RUNNING=$(docker ps --filter "name=athena-langfuse-web" --filter "status=running" -q 2>/dev/null)
            if [ -z "$LANGFUSE_RUNNING" ]; then
                echo "  Langfuse:   Starting Docker containers..."
                docker compose -f "$LANGFUSE_COMPOSE" --env-file "$LANGFUSE_ENV" up -d --quiet-pull 2>/dev/null
                if [ $? -eq 0 ]; then
                    # Wait for web health (up to 60s)
                    TRIES=0
                    while [ $TRIES -lt 12 ]; do
                        if docker ps --filter "name=athena-langfuse-web" --filter "health=healthy" -q 2>/dev/null | grep -q .; then
                            echo "  Langfuse:   Docker stack healthy ✓"
                            break
                        fi
                        TRIES=$((TRIES + 1))
                        sleep 5
                    done
                    if [ $TRIES -eq 12 ]; then
                        echo "  Langfuse:   Docker started (still initializing — check http://localhost:3000)"
                    fi
                else
                    echo "  Langfuse:   Docker start failed — check 'docker compose logs'"
                fi
            else
                echo "  Langfuse:   Docker stack running ✓"
            fi
        else
            echo "  Langfuse:   Docker not running — start Docker Desktop for observability"
        fi
    fi
fi

# ── Kali Backend ──
if grep -q "^KALI_EXTERNAL_URL=.\+" "$ENV_FILE" 2>/dev/null; then
    KALI_URL=$(grep "^KALI_EXTERNAL_URL=" "$ENV_FILE" | cut -d= -f2)
    echo "  Kali:       $KALI_URL ✓"
else
    echo "  Kali:       Not configured"
fi

# ── RAG Knowledge Base (mcp-proxy sidecar) ──
RAG_CONFIG="$DIR/../../.vex-rag.yml"
VEX_RAG_SERVER="/Users/kelvinlomboy/tools/vex-rag/.venv/bin/python3"
VEX_RAG_MODULE="/Users/kelvinlomboy/tools/vex-rag/mcp_server/vex_kb_server.py"
RAG_PROXY_PORT=8765

if command -v mcp-proxy &>/dev/null && [ -f "$VEX_RAG_MODULE" ]; then
    # Check if already running
    RAG_RUNNING=$(lsof -ti:$RAG_PROXY_PORT 2>/dev/null)
    if [ -z "$RAG_RUNNING" ]; then
        ATHENA_ROOT="$(cd "$DIR/../.." && pwd)"
        mcp-proxy \
            --port $RAG_PROXY_PORT --host 127.0.0.1 \
            --transport streamablehttp \
            --cwd "$ATHENA_ROOT" \
            -e RAG_CONFIG "$RAG_CONFIG" \
            -e PYTHONPATH "/Users/kelvinlomboy/tools/vex-rag" \
            -- "$VEX_RAG_SERVER" "$VEX_RAG_MODULE" &>/dev/null &
        RAG_PID=$!
        sleep 2
        if kill -0 $RAG_PID 2>/dev/null; then
            echo "  RAG KB:     mcp-proxy on :$RAG_PROXY_PORT (PID $RAG_PID) ✓"
        else
            echo "  RAG KB:     mcp-proxy failed to start — agents will skip KB searches"
        fi
    else
        echo "  RAG KB:     mcp-proxy already running on :$RAG_PROXY_PORT ✓"
    fi
else
    if ! command -v mcp-proxy &>/dev/null; then
        echo "  RAG KB:     mcp-proxy not installed — run: pip install mcp-proxy"
    else
        echo "  RAG KB:     vex-rag server not found at $VEX_RAG_MODULE"
    fi
fi

echo ""

cd "$DIR" && exec "$VENV/bin/uvicorn" $ARGS
